import type { DashboardStats, LiveCourtInfo, UpcomingBookingInfo, DailyPerformance } from "@/hooks/useManagerDashboard";
import type { GameData } from "@/hooks/useMyGames";
import type { Database } from "@/integrations/supabase/types";

type Court = Database["public"]["Tables"]["courts"]["Row"];
type Venue = Database["public"]["Tables"]["venues"]["Row"];

interface CourtWithVenue extends Court {
  venues: Venue | null;
}

// ─── Player Demo Data ───

// Courts matching CourtWithVenue shape for CourtCard
export const demoCourtsForCards: CourtWithVenue[] = [
  {
    id: "demo-court-1",
    name: "Court A – Indoor",
    venue_id: "demo-v1",
    hourly_rate: 45,
    capacity: 14,
    is_indoor: true,
    is_active: true,
    is_multi_court: false,
    parent_court_id: null,
    allowed_sports: ["futsal", "basketball"],
    ground_type: "hard",
    photo_url: "https://images.unsplash.com/photo-1577223625816-7546f13df25d?w=600&h=400&fit=crop",
    photo_urls: null,
    rules: null,
    payment_timing: "at_booking",
    payment_hours_before: null,
    created_at: "",
    updated_at: "",
    venues: {
      id: "demo-v1",
      name: "Stanley Street Sports Centre",
      address: "44 Stanley St",
      city: "Auckland",
      country: "NZ",
      owner_id: "demo-owner",
      is_active: true,
      slot_interval_minutes: 60,
      max_booking_minutes: 120,
      photo_url: null,
      banner_url: null,
      description: null,
      email: null,
      phone: null,
      latitude: null,
      longitude: null,
      amenities: ["Changing Rooms", "Parking", "Showers"],
      suburb: "Parnell",
      slug: null,
      created_at: "",
      updated_at: "",
    },
  },
  {
    id: "demo-court-2",
    name: "Turf Pitch 1",
    venue_id: "demo-v2",
    hourly_rate: 60,
    capacity: 22,
    is_indoor: false,
    is_active: true,
    is_multi_court: false,
    parent_court_id: null,
    allowed_sports: ["turf_hockey"],
    ground_type: "turf",
    photo_url: "https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?w=600&h=400&fit=crop",
    photo_urls: null,
    rules: null,
    payment_timing: "at_booking",
    payment_hours_before: null,
    created_at: "",
    updated_at: "",
    venues: {
      id: "demo-v2",
      name: "Ellerslie Sports Hub",
      address: "10 Robert St",
      city: "Auckland",
      country: "NZ",
      owner_id: "demo-owner",
      is_active: true,
      slot_interval_minutes: 60,
      max_booking_minutes: 180,
      photo_url: null,
      banner_url: null,
      description: null,
      email: null,
      phone: null,
      latitude: null,
      longitude: null,
      amenities: ["Parking", "Water Fountain"],
      suburb: "Ellerslie",
      slug: null,
      created_at: "",
      updated_at: "",
    },
  },
  {
    id: "demo-court-3",
    name: "Beach Volleyball Court",
    venue_id: "demo-v3",
    hourly_rate: 30,
    capacity: 12,
    is_indoor: false,
    is_active: true,
    is_multi_court: false,
    parent_court_id: null,
    allowed_sports: ["volleyball"],
    ground_type: "sand",
    photo_url: "https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?w=600&h=400&fit=crop",
    photo_urls: null,
    rules: null,
    payment_timing: "at_booking",
    payment_hours_before: null,
    created_at: "",
    updated_at: "",
    venues: {
      id: "demo-v3",
      name: "Mission Bay Recreation",
      address: "2 Tamaki Dr",
      city: "Auckland",
      country: "NZ",
      owner_id: "demo-owner",
      is_active: true,
      slot_interval_minutes: 60,
      max_booking_minutes: 120,
      photo_url: null,
      banner_url: null,
      description: null,
      email: null,
      phone: null,
      latitude: null,
      longitude: null,
      amenities: ["Restrooms", "Parking"],
      suburb: "Mission Bay",
      slug: null,
      created_at: "",
      updated_at: "",
    },
  },
  {
    id: "demo-court-4",
    name: "Tennis Court 2",
    venue_id: "demo-v4",
    hourly_rate: 35,
    capacity: 4,
    is_indoor: false,
    is_active: true,
    is_multi_court: false,
    parent_court_id: null,
    allowed_sports: ["tennis"],
    ground_type: "hard",
    photo_url: "https://images.unsplash.com/photo-1554068865-24cecd4e34b8?w=600&h=400&fit=crop",
    photo_urls: null,
    rules: null,
    payment_timing: "at_booking",
    payment_hours_before: null,
    created_at: "",
    updated_at: "",
    venues: {
      id: "demo-v4",
      name: "Parnell Tennis Club",
      address: "15 Gladstone Rd",
      city: "Auckland",
      country: "NZ",
      owner_id: "demo-owner",
      is_active: true,
      slot_interval_minutes: 60,
      max_booking_minutes: 120,
      photo_url: null,
      banner_url: null,
      description: null,
      email: null,
      phone: null,
      latitude: null,
      longitude: null,
      amenities: ["Parking", "Cafe"],
      suburb: "Parnell",
      slug: null,
      created_at: "",
      updated_at: "",
    },
  },
];

// Groups matching GroupCard props
export const demoGroupCards = [
  {
    id: "demo-group-1",
    name: "Thursday Night Futsal",
    sport: "futsal",
    city: "Auckland",
    memberCount: 14,
    schedule: "Thursdays at 7:00 PM",
    isPublic: true,
    photoUrl: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=400&h=300&fit=crop",
    weeklyPrice: 120,
  },
  {
    id: "demo-group-2",
    name: "Weekend Basketball Crew",
    sport: "basketball",
    city: "Auckland",
    memberCount: 8,
    schedule: "Saturdays at 10:00 AM",
    isPublic: true,
    photoUrl: "https://images.unsplash.com/photo-1546519638-68e109498ffc?w=400&h=300&fit=crop",
    weeklyPrice: 90,
  },
  {
    id: "demo-group-3",
    name: "Tuesday Tennis Social",
    sport: "tennis",
    city: "Auckland",
    memberCount: 6,
    schedule: "Tuesdays at 6:00 PM",
    isPublic: false,
    photoUrl: "https://images.unsplash.com/photo-1622279457486-62dcc4a431d6?w=400&h=300&fit=crop",
    weeklyPrice: 70,
  },
];

// Games matching GameCard / GameData interface
export const demoGameCards: GameData[] = [
  {
    id: "demo-game-1",
    groupName: "Thursday Night Futsal",
    sport: "futsal",
    sportCategory: { id: "sc-futsal", name: "futsal", display_name: "Futsal", icon: "⚽", sort_order: 1, is_active: true, created_at: "", updated_at: "" },
    courtName: "Court A – Indoor",
    venueName: "Stanley Street Sports Centre",
    date: new Date("2026-04-16"),
    time: "19:00",
    endTime: "20:00",
    price: 8.5,
    currentPlayers: 12,
    minPlayers: 10,
    maxPlayers: 14,
    state: "protected",
    isPaid: true,
    durationMinutes: 60,
  },
  {
    id: "demo-game-2",
    groupName: "Weekend Basketball Crew",
    sport: "basketball",
    sportCategory: { id: "sc-basketball", name: "basketball", display_name: "Basketball", icon: "🏀", sort_order: 2, is_active: true, created_at: "", updated_at: "" },
    courtName: "Court B – Outdoor",
    venueName: "Ellerslie Sports Hub",
    date: new Date("2026-04-18"),
    time: "10:00",
    endTime: "11:30",
    price: 12.0,
    currentPlayers: 7,
    minPlayers: 8,
    maxPlayers: 10,
    state: "rescue",
    isPaid: false,
    durationMinutes: 90,
  },
  {
    id: "demo-game-3",
    groupName: "Tuesday Tennis Social",
    sport: "tennis",
    sportCategory: { id: "sc-tennis", name: "tennis", display_name: "Tennis", icon: "🎾", sort_order: 3, is_active: true, created_at: "", updated_at: "" },
    courtName: "Tennis Court 2",
    venueName: "Parnell Tennis Club",
    date: new Date("2026-04-21"),
    time: "18:00",
    endTime: "19:00",
    price: 15.0,
    currentPlayers: 3,
    minPlayers: 4,
    maxPlayers: 4,
    state: "protected",
    isPaid: true,
    durationMinutes: 60,
  },
];

export const demoProfile = {
  fullName: "Alex Johnson",
  email: "alex.johnson@demo.com",
  city: "Auckland",
  phone: "+64 21 555 0123",
  gender: "Male",
  nationality: "NZ",
  preferredSports: ["Futsal", "Basketball", "Tennis"],
  credits: 12.5,
  avatarInitials: "AJ",
  gamesPlayed: 47,
  groupCount: 3,
  showRate: 96,
};

// ─── Manager Demo Data ───

export const demoDashboardStats: DashboardStats = {
  totalBookings: 142,
  revenue: 5420.0,
  utilizationRate: 78,
};

export const demoLiveCourts: LiveCourtInfo[] = [
  {
    court: {
      id: "demo-mc-1",
      name: "Court A – Indoor",
      venue_id: "demo-v1",
      venue_name: "Stanley Street Sports Centre",
      allowed_sports: ["futsal"],
      is_multi_court: false,
      parent_court_id: null,
    },
    status: "in_use",
    currentBooking: {
      bookerName: "Sarah M.",
      remainingMinutes: 25,
      endTime: "20:00",
      progressPercent: 58,
    },
  },
  {
    court: {
      id: "demo-mc-2",
      name: "Court B – Outdoor",
      venue_id: "demo-v1",
      venue_name: "Stanley Street Sports Centre",
      allowed_sports: ["basketball"],
      is_multi_court: false,
      parent_court_id: null,
    },
    status: "upcoming",
    nextBooking: {
      bookerName: "Tom W.",
      startsInMinutes: 45,
      startTime: "20:00",
    },
  },
  {
    court: {
      id: "demo-mc-3",
      name: "Turf Pitch 1",
      venue_id: "demo-v2",
      venue_name: "Ellerslie Sports Hub",
      allowed_sports: ["turf_hockey"],
      is_multi_court: false,
      parent_court_id: null,
    },
    status: "available",
  },
];

export const demoUpcomingBookings: UpcomingBookingInfo[] = [
  {
    id: "demo-b1",
    courtName: "Court A – Indoor",
    venueName: "Stanley Street Sports Centre",
    date: "2026-04-15",
    startTime: "7:00 PM",
    endTime: "8:00 PM",
    durationMinutes: 60,
    bookerName: "Sarah Mitchell",
    bookerInitials: "SM",
    bookerPhone: "+64 21 111 2222",
    paymentStatus: "completed",
    bookingRef: "BK-2026041501",
    courtId: "demo-mc-1",
    venueId: "demo-v1",
    rawStartTime: "19:00",
    rawEndTime: "20:00",
  },
  {
    id: "demo-b2",
    courtName: "Court B – Outdoor",
    venueName: "Stanley Street Sports Centre",
    date: "2026-04-15",
    startTime: "8:00 PM",
    endTime: "9:30 PM",
    durationMinutes: 90,
    bookerName: "Tom Wilson",
    bookerInitials: "TW",
    bookerPhone: "+64 22 333 4444",
    paymentStatus: "pending",
    bookingRef: "BK-2026041502",
    courtId: "demo-mc-2",
    venueId: "demo-v1",
    rawStartTime: "20:00",
    rawEndTime: "21:30",
  },
  {
    id: "demo-b3",
    courtName: "Turf Pitch 1",
    venueName: "Ellerslie Sports Hub",
    date: "2026-04-16",
    startTime: "6:00 PM",
    endTime: "7:30 PM",
    durationMinutes: 90,
    bookerName: "James Lee",
    bookerInitials: "JL",
    bookerPhone: null,
    paymentStatus: "completed",
    bookingRef: "BK-2026041601",
    courtId: "demo-mc-3",
    venueId: "demo-v2",
    rawStartTime: "18:00",
    rawEndTime: "19:30",
  },
];

export const demoWeeklyPerformance: DailyPerformance[] = [
  { day: "Mon", dayShort: "Mon", revenue: 320, bookings: 8 },
  { day: "Tue", dayShort: "Tue", revenue: 480, bookings: 12 },
  { day: "Wed", dayShort: "Wed", revenue: 260, bookings: 6 },
  { day: "Thu", dayShort: "Thu", revenue: 720, bookings: 18 },
  { day: "Fri", dayShort: "Fri", revenue: 540, bookings: 14 },
  { day: "Sat", dayShort: "Sat", revenue: 890, bookings: 22 },
  { day: "Sun", dayShort: "Sun", revenue: 650, bookings: 16 },
];
