import type { DashboardStats, LiveCourtInfo, UpcomingBookingInfo, DailyPerformance } from "@/hooks/useManagerDashboard";

// ─── Player Demo Data ───

export const demoCourts = [
  {
    id: "demo-court-1",
    name: "Court A – Indoor",
    venueName: "Stanley Street Sports Centre",
    city: "Auckland",
    sports: ["Futsal", "Basketball"],
    hourlyRate: 45,
    photoUrl: "https://images.unsplash.com/photo-1577223625816-7546f13df25d?w=600&h=400&fit=crop",
    isIndoor: true,
    capacity: 14,
  },
  {
    id: "demo-court-2",
    name: "Turf Pitch 1",
    venueName: "Ellerslie Sports Hub",
    city: "Auckland",
    sports: ["Turf Hockey"],
    hourlyRate: 60,
    photoUrl: "https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?w=600&h=400&fit=crop",
    isIndoor: false,
    capacity: 22,
  },
  {
    id: "demo-court-3",
    name: "Beach Volleyball Court",
    venueName: "Mission Bay Recreation",
    city: "Auckland",
    sports: ["Volleyball"],
    hourlyRate: 30,
    photoUrl: "https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?w=600&h=400&fit=crop",
    isIndoor: false,
    capacity: 12,
  },
  {
    id: "demo-court-4",
    name: "Tennis Court 2",
    venueName: "Parnell Tennis Club",
    city: "Auckland",
    sports: ["Tennis"],
    hourlyRate: 35,
    photoUrl: "https://images.unsplash.com/photo-1554068865-24cecd4e34b8?w=600&h=400&fit=crop",
    isIndoor: false,
    capacity: 4,
  },
];

export const demoGroups = [
  {
    id: "demo-group-1",
    name: "Thursday Night Futsal",
    sport: "Futsal",
    memberCount: 14,
    maxPlayers: 14,
    day: "Thursday",
    time: "19:00",
    city: "Auckland",
    photoUrl: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=400&h=300&fit=crop",
  },
  {
    id: "demo-group-2",
    name: "Weekend Basketball Crew",
    sport: "Basketball",
    memberCount: 8,
    maxPlayers: 10,
    day: "Saturday",
    time: "10:00",
    city: "Auckland",
    photoUrl: "https://images.unsplash.com/photo-1546519638-68e109498ffc?w=400&h=300&fit=crop",
  },
  {
    id: "demo-group-3",
    name: "Tuesday Tennis Social",
    sport: "Tennis",
    memberCount: 6,
    maxPlayers: 8,
    day: "Tuesday",
    time: "18:00",
    city: "Auckland",
    photoUrl: "https://images.unsplash.com/photo-1622279457486-62dcc4a431d6?w=400&h=300&fit=crop",
  },
];

export const demoGames = [
  {
    id: "demo-game-1",
    groupName: "Thursday Night Futsal",
    sport: "Futsal",
    date: "2026-04-16",
    time: "19:00",
    courtName: "Court A – Indoor",
    venueName: "Stanley Street Sports Centre",
    playersConfirmed: 12,
    maxPlayers: 14,
    status: "protected" as const,
    pricePerPlayer: 8.5,
  },
  {
    id: "demo-game-2",
    groupName: "Weekend Basketball Crew",
    sport: "Basketball",
    date: "2026-04-18",
    time: "10:00",
    courtName: "Court B – Outdoor",
    venueName: "Ellerslie Sports Hub",
    playersConfirmed: 7,
    maxPlayers: 10,
    status: "protected" as const,
    pricePerPlayer: 12.0,
  },
  {
    id: "demo-game-3",
    groupName: "Tuesday Tennis Social",
    sport: "Tennis",
    date: "2026-04-21",
    time: "18:00",
    courtName: "Tennis Court 2",
    venueName: "Parnell Tennis Club",
    playersConfirmed: 3,
    maxPlayers: 4,
    status: "rescue" as const,
    pricePerPlayer: 15.0,
  },
];

export const demoProfile = {
  fullName: "Alex Johnson",
  email: "alex.johnson@demo.com",
  city: "Auckland",
  phone: "+64 21 555 0123",
  gender: "Male",
  nationality: "NZ",
  preferredSports: ["Futsal", "Basketball", "Tennis"],
  credits: 12.5,
  avatarInitials: "AJ",
};

// ─── Manager Demo Data ───

export const demoDashboardStats: DashboardStats = {
  totalBookings: 142,
  revenue: 5420.0,
  utilizationRate: 78,
};

export const demoLiveCourts: LiveCourtInfo[] = [
  {
    court: {
      id: "demo-mc-1",
      name: "Court A – Indoor",
      venue_id: "demo-v1",
      venue_name: "Stanley Street Sports Centre",
      allowed_sports: ["futsal"],
      is_multi_court: false,
      parent_court_id: null,
    },
    status: "in_use",
    currentBooking: {
      bookerName: "Sarah M.",
      remainingMinutes: 25,
      endTime: "20:00",
      progressPercent: 58,
    },
  },
  {
    court: {
      id: "demo-mc-2",
      name: "Court B – Outdoor",
      venue_id: "demo-v1",
      venue_name: "Stanley Street Sports Centre",
      allowed_sports: ["basketball"],
      is_multi_court: false,
      parent_court_id: null,
    },
    status: "upcoming",
    nextBooking: {
      bookerName: "Tom W.",
      startsInMinutes: 45,
      startTime: "20:00",
    },
  },
  {
    court: {
      id: "demo-mc-3",
      name: "Turf Pitch 1",
      venue_id: "demo-v2",
      venue_name: "Ellerslie Sports Hub",
      allowed_sports: ["turf_hockey"],
      is_multi_court: false,
      parent_court_id: null,
    },
    status: "available",
  },
];

export const demoUpcomingBookings: UpcomingBookingInfo[] = [
  {
    id: "demo-b1",
    courtName: "Court A – Indoor",
    venueName: "Stanley Street Sports Centre",
    date: "2026-04-15",
    startTime: "7:00 PM",
    endTime: "8:00 PM",
    durationMinutes: 60,
    bookerName: "Sarah Mitchell",
    bookerInitials: "SM",
    bookerPhone: "+64 21 111 2222",
    paymentStatus: "completed",
    bookingRef: "BK-2026041501",
    courtId: "demo-mc-1",
    venueId: "demo-v1",
    rawStartTime: "19:00",
    rawEndTime: "20:00",
  },
  {
    id: "demo-b2",
    courtName: "Court B – Outdoor",
    venueName: "Stanley Street Sports Centre",
    date: "2026-04-15",
    startTime: "8:00 PM",
    endTime: "9:30 PM",
    durationMinutes: 90,
    bookerName: "Tom Wilson",
    bookerInitials: "TW",
    bookerPhone: "+64 22 333 4444",
    paymentStatus: "pending",
    bookingRef: "BK-2026041502",
    courtId: "demo-mc-2",
    venueId: "demo-v1",
    rawStartTime: "20:00",
    rawEndTime: "21:30",
  },
  {
    id: "demo-b3",
    courtName: "Turf Pitch 1",
    venueName: "Ellerslie Sports Hub",
    date: "2026-04-16",
    startTime: "6:00 PM",
    endTime: "7:30 PM",
    durationMinutes: 90,
    bookerName: "James Lee",
    bookerInitials: "JL",
    bookerPhone: null,
    paymentStatus: "completed",
    bookingRef: "BK-2026041601",
    courtId: "demo-mc-3",
    venueId: "demo-v2",
    rawStartTime: "18:00",
    rawEndTime: "19:30",
  },
];

export const demoWeeklyPerformance: DailyPerformance[] = [
  { day: "Mon", dayShort: "Mon", revenue: 320, bookings: 8 },
  { day: "Tue", dayShort: "Tue", revenue: 480, bookings: 12 },
  { day: "Wed", dayShort: "Wed", revenue: 260, bookings: 6 },
  { day: "Thu", dayShort: "Thu", revenue: 720, bookings: 18 },
  { day: "Fri", dayShort: "Fri", revenue: 540, bookings: 14 },
  { day: "Sat", dayShort: "Sat", revenue: 890, bookings: 22 },
  { day: "Sun", dayShort: "Sun", revenue: 650, bookings: 16 },
];
